# Generated by Django 5.1.7 on 2025-10-28 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('reported', models.BooleanField(default=False)),
                ('reports', models.ManyToManyField(blank=True, related_name='expenses', to='users.report')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shift')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.waiter')),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'menu category',
                'verbose_name_plural': 'menu categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='orders_menu_name_e4d472_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='menu_items/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('customer_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('staff_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='orders.menucategory')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='orders_menu_id_234f5b_idx'), models.Index(fields=['name'], name='orders_menu_name_74ab71_idx'), models.Index(fields=['-created'], name='orders_menu_created_cc9b8e_idx')],
            },
        ),
    ]
